stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    outs:
    - data/raw
  pre_processing:
    cmd: python src/data_prep.py
    deps:
    - data/raw
    - src/data_prep.py
    outs:
    - data/processed_data
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed_data
    - src/model_building.py
    outs:
    - models/model_rf_v1.pkl
  model_eval:
    cmd: python src/model_eval.py
    deps:
    - models/model_rf_v1.pkl
    - src/model_eval.py
    metrics:
    - metrics.json
