stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  pre_preprocessing:
    cmd: python src/data_prep.py
    deps:
    - data/raw
    - src/data_prep.py
    outs:
    - data/processed_data
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/processed_data
    - src/model_building.py
    params:
    - model_building.n_estimators
    outs:
    - models/model.pkl
  model_eval:
    cmd: python src/model_eval.py
    deps:
    - models/model.pkl
    - src/model_eval.py
    metrics:
    - reports/metrics.json
    outs:
    - reports/run_info.json


  model_registration:
    cmd: python src/model_reg.py
    deps:
    - reports/run_info.json
    - src/model_reg.py